services:
  django:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: django
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - postgres_db
    command: sh ./docker/startup.sh
    volumes:
      - static_volume:/tur/back_static/
      - media_volume:/tur/back_media/
      - ../:/tur/

  postgres_db:
    image: postgres:14.3-alpine
    container_name: postgres_db
    ports:
      - "5432:5432"
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure

  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - django
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/tur/back_static/
      - media_volume:/tur/back_media/

volumes:
  postgres_data:
  static_volume:
  media_volume:
